//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_service
    {
        public int servicedıd { get; set; }
        public string serviceTitle { get; set; }
        public string Description { get; set; }
        public string IconUrl { get; set; }
    }
}
