//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunmedyaAkademiPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkimda
    {
        public string dogumtarihi { get; set; }
        public int aboutid { get; set; }
        public string yas { get; set; }
        public string website { get; set; }
        public string telefon { get; set; }
        public string sehir { get; set; }
        public string email { get; set; }
        public string freelance { get; set; }
        public string hakkimdabaslik { get; set; }
        public string hakkimdaaçiklama { get; set; }
        public string kisaaciklama { get; set; }
        public string egitim { get; set; }
    }
}
